#!/bin/bash

NAME=$1
echo "Opening codespace $NAME"
# Copy auth details for atuin

gh cs cp --codespace $NAME -e ~/.config/atuin_login 'remote:/workspaces/.atuin_login' &
gh cs cp --codespace $NAME -e ~/.dotfile_groups/codespaces/hosts 'remote:/etc/hosts' &

cp ~/.config/wezterm/codespace_template.lua /tmp/codespace_$NAME.lua
sed -i "s/CS_NAME/${NAME}/g" /tmp/codespace_$NAME.lua

wezterm --config-file /tmp/codespace_$NAME.lua connect "${NAME}" &

# Start the codespace in vscode in background
gh cs code --codespace $NAME --insiders