#!/bin/bash

set -e

sudo echo "Getting sudo permissions"

# sudo timeshift --create --comments "before exec update-linux" --tags W || echo "Failed to take timeshift snapshot"

# Do updating
flatpak update -y
sudo apt update
sudo apt upgrade -y
brew update
brew upgrade

# Get latest dotfiles
chezmoi update

sudo snap refresh || echo "failed to update snap packages"
rustup update || echo "failed to update rust tooling" 
# Get firmware updates
fwupdmgr get-updates

echo "Update completed!"