#!/bin/bash

set -e


function get_recent_workspaces()
{
    gh codespace list --json name,gitStatus,lastUsedAt,repository \
        --template "{{range .}}{{.repository}} {{.gitStatus.ref}} last used: {{ slice .lastUsedAt 8 }} _ {{.name}};{{end}}" \
        | tr ';' '\n' 
}


WORKSPACE=$( (echo empty; get_recent_workspaces)  | rofi -dmenu -p "Select Codespace:")

if [ x"empty" = x"${WORKSPACE}" ]
then
    code
elif [ -n "${WORKSPACE}" ]
then
    NAME=$(echo $WORKSPACE | cut --delimiter="_" --fields=2) 
    echo "Opening codespace $NAME"
    gh cs code --codespace $NAME --insiders
fi