#!/bin/bash

set -e

sudo timeshift --create --comments "before exec update-linux" --tags W

# Get latest dotfiles
chezmoi update

# Do updating
flatpak update -y
sudo apt update
sudo apt upgrade -y
brew update
brew upgrade
#sudo snap refresh

# Todo: add optional fwupdmgr command based on "would you like to check and update firmware too? y/n" prompt

echo "Update completed!"